### ISSUE TITLE
Problem when going from NORTH to SOUTH

### ISSUE THREAD

**Issue by TheMutley** [PDXostc/can_firewall_software#2]
I've assembled one CAN Firewall and it work fine. The only problem I have right now is when I'm sending  CAN data from the CAR CAN port to the IVI CAN, everything works fine with a propagation delay of approx 1 ms. When I reverse the flow (i.e. sending CAN data from IVI to the CAR), I lose packet, and other are sent much more often then intended. Also, some new packet are created randomly. The rules are the same for both port and allow everything to go through. Any ideas what could be the problem ? 

Here's a screenshot when it's working fine  ( CAR to IVI) : 
![image](https://cloud.githubusercontent.com/assets/18019758/21654752/f1f51b2c-d284-11e6-9d6f-e81fb4aad16e.png)

Here's a screenshot when there's a problem ( IVI to CAR) : 
![image](https://cloud.githubusercontent.com/assets/18019758/21654761/ff8ea578-d284-11e6-859c-71a68adcc81b.png)

**Comment by smiller6** [comment]
Hugo,

First, thanks for checking this project out! My hat is off to you for navigating the lack of proper documentation on the software side and figuring out how to get it up and running.

I'll admit from the screen shot you posted and the description provided I would not be able to guess right away what might be causing the issue you are seeing.

Based on the description, the first suspect would likely be an issue with the rule set. Please forgive me for suggesting this, as you've already stated that they are identical and that they are simply set to allow for full pass through.

Is the CAN traffic and analysis being run in a fully simulated network environment (like CANAlyser), or are there any live devices or nodes involved? I'm wondering if there are any variables in the hardware setup. Does simply "flipping" the Firewall device around produce identical or different results? (If it's an issue internal to the firewall then reversing the North/South arrangement should show the same results?)

The delay is a perplexing problem, however. We don't have enough information here to go on yet, but the delay brings up the possibility of something in hardware being incorrectly configured, or perhaps something is slightly at issue with the interrupts. What modifications have you had to make to get the firmware up and running on your development board?

Did you build a board identical to our spec or have you made adaptations?

You're no doubt ahead of me on troubleshooting the problem, so apologies for covering ground you've likely checked.

Steve

**Comment by TheMutley** [comment]
Now that it work on both side, I'm impressed with the results! Both CAN bus are set at 500kbps, I manage to load them up to 90% along with couple of messages sent every 1 ms, and everything seem to be there!

![image](https://cloud.githubusercontent.com/assets/18019758/21667734/77034188-d2c9-11e6-9fac-2b486e0d9f5f.png)

**Comment by smiller6** [comment]
Good to hear! Thank you again for finding that significant error.
Pull request fixing this issue has been accepted.
I'm glad your test results are working well. Our informal testing suggested that at a 10ms message interval (standard for some CAN), the firewall should be able to achieve a throughput of nearly 2mbps. I'd love to hear if your results are similar, and if the device is able to perform well in whatever you end up using it for.
Cheers.

**Comment by toxicgumbo** [comment]
Not to digress, but: Hugo, if your build and configuration experience can lend to additional documentation, that might make for a nice pull request as well. :-)  Great job getting things together and for finding this issue. 

Steve, it's encouraging to see such a quick turnaround.

**Comment by TheMutley** [comment]
I will for sure!
